<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25086" started-at="2020-02-13T06:21:19Z" finished-at="2020-02-13T06:21:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25086" started-at="2020-02-13T06:21:19Z" finished-at="2020-02-13T06:21:44Z">
      <class name="com.training.sanity.tests.MediumTests">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.MediumTests@27efef64]" name="setUpBeforeClass" is-config="true" duration-ms="13084" started-at="2020-02-13T06:21:19Z" finished-at="2020-02-13T06:21:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="validLoginTest()[pri:0, instance:com.training.sanity.tests.MediumTests@27efef64]" name="validLoginTest" duration-ms="1268" started-at="2020-02-13T06:21:32Z" finished-at="2020-02-13T06:21:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.MediumTests@27efef64]" name="tearDown" is-config="true" duration-ms="1001" started-at="2020-02-13T06:21:33Z" finished-at="2020-02-13T06:21:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="transaction()[pri:1, instance:com.training.sanity.tests.MediumTests@27efef64]" name="transaction" duration-ms="4816" started-at="2020-02-13T06:21:34Z" finished-at="2020-02-13T06:21:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- transaction -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.MediumTests@27efef64]" name="tearDown" is-config="true" duration-ms="1000" started-at="2020-02-13T06:21:39Z" finished-at="2020-02-13T06:21:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="validLoginTest1()[pri:2, instance:com.training.sanity.tests.MediumTests@27efef64]" name="validLoginTest1" duration-ms="686" started-at="2020-02-13T06:21:40Z" finished-at="2020-02-13T06:21:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.MediumTests@27efef64]" name="tearDown" is-config="true" duration-ms="1007" started-at="2020-02-13T06:21:41Z" finished-at="2020-02-13T06:21:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="accinfo()[pri:3, instance:com.training.sanity.tests.MediumTests@27efef64]" name="accinfo" duration-ms="1179" started-at="2020-02-13T06:21:42Z" finished-at="2020-02-13T06:21:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [birth day gift]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [birth day gift]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.training.pom.AccinfoPOM.clickAccinfo(AccinfoPOM.java:34)
at com.training.sanity.tests.MediumTests.accinfo(MediumTests.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accinfo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.MediumTests@27efef64]" name="tearDown" is-config="true" duration-ms="1000" started-at="2020-02-13T06:21:43Z" finished-at="2020-02-13T06:21:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.MediumTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
